version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install --only=production
  build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
